### ISSUE TITLE
Emails haven't arrived in the mail 

### ISSUE THREAD

**Issue by bughunterqa** [phstc/putsbox#49]
Hi, Currently, emails haven't arrived in the mail for the last 4 days. Could you please check this issue

**Comment by ituradastra** [comment]
Experiencing the same issue

**Comment by maris-salenieks** [comment]
Me three experiencing the same issue

**Comment by rajguru016** [comment]
experiencing the same issue since last 3-4 days

**Comment by phstc** [comment]
Sorry for experiencing this issue. 

SendGrid suddenly disabled the PutsBox account because of service inactivity (how? PutsBox is used daily).

We've just configured a new account (with the help of SendGrid's support, they did good here), and it should be working now. 

Can you give it a try again?

**Comment by uniqa-lv** [comment]
Now e-mails are coming.
But I see the error: This email does not have a html version

**Comment by phstc** [comment]
@uniqa-lv sorry, it was a bad SendGrid configuration. Should be fixed by now. Can you check it again?

**Comment by uniqa-lv** [comment]
@phstc checked, still same error - This email does not have a html version

**Comment by phstc** [comment]
@uniqa-lv sorry, the fix is only for emails created after the fix. Can you test it with a new email?

**Comment by uniqa-lv** [comment]
@phstc just have checked with new email, still see same error

**Comment by phstc** [comment]
I'm sorry again. It worked on my test. But you are right, it was not working after.

I updated the configuration again, and it's back.

Can you give another try with a new email?

For further reference, these two options need to be disabled on the incoming API parser configuration.

- POST the raw, full MIME message
- Check incoming emails for spam

**Comment by uniqa-lv** [comment]
Hi @phstc , I am able to see e-mail body, thank you!

**Comment by bughunterqa** [comment]
Hi @phstc, thanks a lot for the fix

**Comment by ituradastra** [comment]
@phstc Thanks for the fix  :)  . Everything works fine
